# Generated by Django 3.2.12 on 2023-12-29 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('MEETING', 'MEETING'), ('LECTURE', 'LECTURE'), ('CONCERT', 'CONCERT'), ('SEMINAR', 'SEMINAR'), ('STUDY', 'STUDY')], max_length=256)),
                ('capacity', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField(null=True)),
                ('weekly', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('open_time', models.CharField(max_length=256)),
                ('close_time', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissionForRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('WRITE', 'WRITE'), ('LIST', 'LIST'), ('RESERVE', 'RESERVE'), ('PERRESERVE', 'PERRESERVE'), ('DELETE', 'DELETE')], max_length=256)),
                ('room', models.ManyToManyField(related_name='permissions', to='RoomReservation.Room')),
                ('user', models.ManyToManyField(related_name='room_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissionForOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('LIST', 'LIST'), ('ADD', 'ADD'), ('ACCESS', 'ACCESS'), ('DELETE', 'DELETE')], max_length=256)),
                ('organization', models.ManyToManyField(related_name='permissions', to='RoomReservation.Organization')),
                ('user', models.ManyToManyField(related_name='organization_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissionForEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('WRITE', 'WRITE'), ('READ', 'READ')], max_length=256)),
                ('event', models.ManyToManyField(related_name='permissions', to='RoomReservation.Event')),
                ('user', models.ManyToManyField(related_name='event_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomInOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ManyToManyField(related_name='rooms', to='RoomReservation.Organization')),
                ('room', models.ManyToManyField(related_name='organizations', to='RoomReservation.Room')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='RoomReservation.room'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
