# Generated by Django 5.0 on 2023-12-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomReservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='RoomReservation.organization'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoomInOrganization',
        ),
    ]
