# Generated by Django 3.2.12 on 2024-01-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomReservation', '0002_room_organization_delete_roominorganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='weekly',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
